import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Physical AI & Humanoid Robotics textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro/physical-ai-overview', 'intro/embodied-intelligence', 'intro/why-physical-ai', 'intro/ui-demo'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/ros2-intro',
        'module-1-ros2/nodes-topics-services',
        'module-1-ros2/rclpy-bridge',
        'module-1-ros2/urdf-humanoids',
        'module-1-ros2/ros2-exercises'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-simulation/gazebo-intro',
        'module-2-simulation/physics-simulation',
        'module-2-simulation/unity-hri',
        'module-2-simulation/sensor-modeling',
        'module-2-simulation/simulation-exercises'
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3-isaac/isaac-intro',
        'module-3-isaac/isaac-sim',
        'module-3-isaac/isaac-ros',
        'module-3-isaac/nav2-bipedal',
        'module-3-isaac/isaac-exercises'
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/vla-intro',
        'module-4-vla/voice-to-action',
        'module-4-vla/cognitive-planning',
        'module-4-vla/capstone-project',
        'module-4-vla/vla-exercises'
      ],
    },
    {
      type: 'category',
      label: 'Hardware Setup & Requirements',
      items: [
        'hardware-setup/workstation-setup',
        'hardware-setup/edge-kits',
        'hardware-setup/robot-options',
        'hardware-setup/cloud-alternatives'
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [
        'appendices/ros2-cheatsheet',
        'appendices/simulation-tips',
        'appendices/troubleshooting',
        'appendices/glossary',
        'appendices/resources'
      ],
    }
  ],
};

export default sidebars;
